--- #YAML:1.0
name:               Net-IMAP-Simple
version:            1.1913
abstract:           ~
author:
    - Paul Miller <jettero@cpan.org>
license:            Perl Artistic
distribution_type:  module
configure_requires:
    Class::Accessor:      0
    Coro:                 0
    DateTime:             0
    DateTime::Format::Mail:  0
    DateTime::Format::Strptime:  0
    Email::Address:       0
    Email::MIME:          1.862
    Email::MIME::ContentType:  0
    Email::Simple:        1.999
    Encode::IMAPUTF7:     0
    List::MoreUtils:      0
    MIME::Base64:         0
    Net::Server::Coro:    0.3
    Net::SSLeay:          0
    Regexp::Common:       0
    Test::More:           0
    UNIVERSAL::require:   0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Select:  0
    IO::Socket:  0
    perl:        5.008
resources:
    repository:  http://github.com/jettero/net--imap--simple
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - imap
    - simple
